In [99]:
import pandas as pd
import numpy as np

CLASSIFICATION AND SPLIT

In [100]:
df=pd.read_csv(r'C:\Users\bachu\Desktop\5thsem_OJT\project1_diabetes\data\processed\muhammed_bilal_p1w2_features.csv',parse_dates=['last_checkup_date'])

In [101]:
df.shape

(950, 21)

In [102]:
df['outcome'].value_counts(normalize=True)

outcome
0    0.712632
1    0.287368
Name: proportion, dtype: float64

In [103]:
feature_cols = [' age','pregnancies','glucose','blood_pressure','skin_thickness','insulin','bmi','diabetes_pedigree','bmi_category','glucose_band']

seprate the featurees from the target

In [104]:
feature_cols =['age','pregnancies','glucose','blood_pressure','skin_thickness','insulin','bmi','diabetes_pedigree','bmi_category','glucose_band']
x=df[feature_cols]
y=df['outcome']

In [105]:
x

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi_category,glucose_band
0,79,0,124.0,71.0,30.0,124.0,23.4,0.588,normal,prediabetic
1,37,0,153.0,85.0,24.0,42.0,33.9,0.192,obese,diabetic
2,39,0,142.0,68.0,22.0,159.0,26.9,0.777,overweight,diabetic
3,68,7,121.0,88.0,26.0,124.0,29.0,1.217,overweight,prediabetic
4,75,0,107.0,84.0,31.0,101.0,21.2,0.278,normal,prediabetic
...,...,...,...,...,...,...,...,...,...,...
945,64,2,117.0,81.0,34.0,124.0,40.3,0.641,obese,prediabetic
946,71,0,140.0,64.0,37.0,124.0,33.4,0.116,obese,diabetic
947,40,0,130.0,73.0,26.0,258.0,20.1,0.709,normal,diabetic
948,52,4,123.0,76.0,22.0,189.0,38.9,0.540,obese,prediabetic
949,42,0,114.0,73.0,34.0,124.0,28.2,0.819,overweight,prediabetic

In [106]:
y

0      0
1      1
2      0
3      1
4      0
      ..
945    0
946    1
947    0
948    0
949    0
Name: outcome, Length: 950, dtype: int64

encode your banded features

In [107]:
x=pd.get_dummies(x,drop_first=True)
#drop_first is used for after new column add before column removing function 
#get dummies is  used for value to numerical value function  
x.shape

(950, 13)

In [108]:
df

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,...,smoker,last_checkup_date,outcome,age_band,bmi_category,glucose_band,insulin_glucose_ratio,pregnancies_age_rate,since_checkup,activity_smoker
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,...,NO,2023-04-20,0,senior,normal,prediabetic,1.000000,0.000000,618,Unknown/NO
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,...,YES,2024-05-03,1,middle-aged,obese,diabetic,0.274510,0.000000,239,Medium/YES
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,...,UNKNOWN,2023-07-08,0,middle-aged,overweight,diabetic,1.119718,0.000000,539,Low/UNKNOWN
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,...,YES,2024-04-14,1,senior,overweight,prediabetic,1.024793,0.102941,258,Unknown/YES
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,...,NO,2024-01-27,0,senior,normal,prediabetic,0.943925,0.000000,336,Low/NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,P00338,64,male,2,117.0,81.0,34.0,124.0,40.3,0.641,...,YES,2023-11-17,0,senior,obese,prediabetic,1.059829,0.031250,407,Medium/YES
946,P00092,71,female,0,140.0,64.0,37.0,124.0,33.4,0.116,...,YES,2023-05-20,1,senior,obese,diabetic,0.885714,0.000000,588,Low/YES
947,P00081,40,female,0,130.0,73.0,26.0,258.0,20.1,0.709,...,NO,2023-06-07,0,middle-aged,normal,diabetic,1.984615,0.000000,570,Low/NO
948,P00704,52,female,4,123.0,76.0,22.0,189.0,38.9,0.540,...,NO,2024-06-05,0,middle-aged,obese,prediabetic,1.536585,0.076923,206,High/NO
949,P00922,42,male,0,114.0,73.0,34.0,124.0,28.2,0.819,...,NO,2023-10-10,0,middle-aged,overweight,prediabetic,1.087719,0.000000,445,Medium/NO

In [109]:
x

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi_category_obese,bmi_category_overweight,bmi_category_underweight,glucose_band_normal,glucose_band_prediabetic
0,79,0,124.0,71.0,30.0,124.0,23.4,0.588,False,False,False,False,True
1,37,0,153.0,85.0,24.0,42.0,33.9,0.192,True,False,False,False,False
2,39,0,142.0,68.0,22.0,159.0,26.9,0.777,False,True,False,False,False
3,68,7,121.0,88.0,26.0,124.0,29.0,1.217,False,True,False,False,True
4,75,0,107.0,84.0,31.0,101.0,21.2,0.278,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,64,2,117.0,81.0,34.0,124.0,40.3,0.641,True,False,False,False,True
946,71,0,140.0,64.0,37.0,124.0,33.4,0.116,True,False,False,False,False
947,40,0,130.0,73.0,26.0,258.0,20.1,0.709,False,False,False,False,False
948,52,4,123.0,76.0,22.0,189.0,38.9,0.540,True,False,False,False,True
949,42,0,114.0,73.0,34.0,124.0,28.2,0.819,False,True,False,False,True

split into trainning and test sets

In [110]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(
    x,y, test_size=0.2, random_state=42, stratify=y)

In [111]:
x_test

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi_category_obese,bmi_category_overweight,bmi_category_underweight,glucose_band_normal,glucose_band_prediabetic
764,43,3,138.0,72.0,44.0,124.0,21.2,0.524,False,False,False,False,False
224,27,2,73.0,87.0,34.0,160.0,27.8,0.625,False,True,False,True,False
333,21,6,133.0,77.0,18.0,10.0,32.3,0.379,True,False,False,False,False
685,55,7,114.0,82.0,10.0,188.0,28.5,0.153,False,True,False,False,True
845,42,5,111.0,79.0,26.0,94.0,35.2,0.184,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,72,0,88.0,79.0,26.0,124.0,43.2,0.606,True,False,False,True,False
748,65,0,104.0,48.0,24.0,28.0,32.8,0.680,True,False,False,False,True
947,40,0,130.0,73.0,26.0,258.0,20.1,0.709,False,False,False,False,False
514,69,0,190.0,86.0,23.0,51.0,38.1,0.470,True,False,False,False,False
789,41,0,123.0,78.0,15.0,124.0,30.3,0.372,True,False,False,False,True

In [112]:
x_test.shape

(190, 13)

In [113]:
x_train.shape

(760, 13)

In [114]:
y_test.value_counts(normalize=True)

outcome
0    0.710526
1    0.289474
Name: proportion, dtype: float64

BUILDING THE BASELINE

import your model and scaler

In [115]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

scale your features

In [116]:
scaler = StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled= scaler.transform(x_test)

In [117]:
x_test_scaled

array([[-0.40233827,  0.41776224,  0.71871423, ..., -0.19557956,
        -0.62605223, -0.72956019],
       [-1.3101938 ,  0.04023632, -1.57871576, ..., -0.19557956,
         1.59731082, -0.72956019],
       [-1.65063962,  1.55034   ,  0.54198885, ..., -0.19557956,
        -0.62605223, -0.72956019],
       ...,
       [-0.57256119, -0.71481553,  0.43595362, ..., -0.19557956,
        -0.62605223, -0.72956019],
       [ 1.07292695, -0.71481553,  2.55665823, ..., -0.19557956,
        -0.62605223, -0.72956019],
       [-0.51582022, -0.71481553,  0.18853808, ..., -0.19557956,
        -0.62605223,  1.37068883]], shape=(190, 13))

fit the baseline model

In [118]:
model = LogisticRegression(max_iter=1000)
model.fit(x_train_scaled, y_train)

LogisticRegression(max_iter=1000)

predict on the test set

In [119]:
y_pred = model.predict (x_test_scaled)
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

eyeball the first ten prediction

In [120]:
pd.DataFrame({"actual":y_test.values[:10],
             "predicted":y_pred[:10]})

   actual  predicted
0       0          0
1       0          0
2       0          0
3       0          0
4       1          0
5       0          0
6       0          0
7       1          0
8       0          0
9       0          0

compute test accuracy

In [121]:
from sklearn.metrics import accuracy_score
test_acc=accuracy_score (y_test,y_pred)
print("test_accuracy =",test_acc)

test_accuracy = 0.7526315789473684

In [123]:
train_acc=accuracy_score(y_train,model.predict(x_train_scaled))
print(train_acc,test_acc)
print(train_acc-test_acc)

0.7394736842105263 0.7526315789473684
-0.013157894736842146

read the model"s conflict

In [128]:
coefs = pd.Series(model.coef_[0],index=x.columns)
coefs

age                         0.491415
pregnancies                 0.038386
glucose                     0.735806
blood_pressure             -0.079049
skin_thickness              0.008264
insulin                     0.145549
bmi                         0.013526
diabetes_pedigree           0.315160
bmi_category_obese          0.229851
bmi_category_overweight    -0.012606
bmi_category_underweight   -0.068772
glucose_band_normal        -0.183426
glucose_band_prediabetic    0.028700
dtype: float64

In [129]:
coefs = pd.Series(model.coef_[0],index=x.columns)
coefs.abs().sort_values(ascending=False)

glucose                     0.735806
age                         0.491415
diabetes_pedigree           0.315160
bmi_category_obese          0.229851
glucose_band_normal         0.183426
insulin                     0.145549
blood_pressure              0.079049
bmi_category_underweight    0.068772
pregnancies                 0.038386
glucose_band_prediabetic    0.028700
bmi                         0.013526
bmi_category_overweight     0.012606
skin_thickness              0.008264
dtype: float64

In [130]:
coefs = pd.Series(model.coef_[0], index=x.columns)
rank = coefs.reindex(coefs.abs().sort_values(ascending=False).index)
rank

glucose                     0.735806
age                         0.491415
diabetes_pedigree           0.315160
bmi_category_obese          0.229851
glucose_band_normal        -0.183426
insulin                     0.145549
blood_pressure             -0.079049
bmi_category_underweight   -0.068772
pregnancies                 0.038386
glucose_band_prediabetic    0.028700
bmi                         0.013526
bmi_category_overweight    -0.012606
skin_thickness              0.008264
dtype: float64